version: "3.4"
services:
  squid:
    image: ubuntu/squid
    restart: always
    container_name: squid
    hostname: squid
    volumes:
      - ./squid.conf:/etc/squid/squid.conf
      - ./logs:/var/log/squid
    ports:
      - 127.0.0.1:3128:3128
